### ISSUE TITLE
Invalid kms arn issue with aws-centergauge topic

### ISSUE THREAD

**Issue by siddarthancha** [truemark/cdk#156]
Invalid arn arn:aws:kms:us-west-2:<AccountId>:aws/sns (Service: AWSKMS; Status Code: 400; Error Code: NotFoundException; Request ID: 8eeed77c-a3f8-4768-8874-283892326e61; Proxy: null) (Service: AmazonSNS; Status Code: 400; Error Code: KMSNotFound; Request ID: 3e0b3a2f-4c93-5ce9-8fe1-64cdda39e2c5; Proxy: null)"

**Comment by erikrj** [comment]
I believe this was fixed in https://github.com/truemark/cdk/pull/157. If not, feel free to re-open.
