### ISSUE TITLE
Issue with using the StandardFargateSerice

### ISSUE THREAD

**Issue by tvc123** [truemark/cdk#164]
There is an issue calling the StandardFargateService it defines a grace period which is an invalid parameter for a service that isn't connected to a load balancer

Resource handler returned message: "Invalid request provided: CreateService error: Health check grace period is only valid for services configured to use load balancers (Service: Ama
zonECS; Status Code: 400; Error Code: InvalidParameterException; Request ID: XXXed; Proxy: null)" (RequestToken: XXXXXXX8,
HandlerErrorCode: InvalidRequest)

https://github.com/truemark/cdk/blob/d55347e0b8da368a6a5b754b73f422c20ed92c43/aws-ecs/lib/standard-fargate-service.ts#L448C1-L449C62

**Comment by erikrj** [comment]
This has been released in version 1.13.2.
